using Microsoft.EntityFrameworkCore;

namespace ShoeSales.Models
{
    public static class ModelBuilderExtension
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Category>().HasData(
                new Category { Id = 1, CategoryName = "Sneakers" },
                new Category { Id = 2, CategoryName = "Dress Shoes" },
                new Category { Id = 3, CategoryName = "Casual" },
                new Category { Id = 4, CategoryName = "Loafers" },
                new Category { Id = 5, CategoryName = "Boots" });
            modelBuilder.Entity<Product>().HasData(
                new Product { Id = 1, CategoryId = 1, Brand = "New Balance", Name = "Two WXY", Location = "Main", Size = 7, Price = 101.55M, IsAvailable = true },
                new Product { Id = 2, CategoryId = 1, Brand = "New Balance", Name = "Two WXY", Location = "Main", Size = 8, Price = 101.55M, IsAvailable = true },
                new Product { Id = 3, CategoryId = 1, Brand = "New Balance", Name = "Two WXY", Location = "Main", Size = 9, Price = 101.55M, IsAvailable = true },
                new Product { Id = 4, CategoryId = 1, Brand = "New Balance", Name = "2002R", Location = "Main", Size = 10, Price = 99M, IsAvailable = true },
                new Product { Id = 5, CategoryId = 1, Brand = "New Balance", Name = "2002R", Location = "Main", Size = 11, Price = 99M, IsAvailable = true },
                new Product { Id = 6, CategoryId = 1, Brand = "New Balance", Name = "2002R", Location = "Main", Size = 12, Price = 99M, IsAvailable = true },
                new Product { Id = 7, CategoryId = 1, Brand = "New Balance", Name = "Fresh Foam 1080", Location = "Main", Size = 7, Price = 100.99M, IsAvailable = true },
                new Product { Id = 8, CategoryId = 1, Brand = "New Balance", Name = "Fresh Foam 1080", Location = "Main", Size = 8, Price = 100.99M, IsAvailable = true },
                new Product { Id = 9, CategoryId = 1, Brand = "New Balance", Name = "Fresh Foam 1080", Location = "Main", Size = 9, Price = 100.99M, IsAvailable = true },
                new Product { Id = 10, CategoryId = 1, Brand = "Converse", Name = "Chuck Taylor All Star", Location = "Main", Size = 7, Price = 101.55M, IsAvailable = true },
                new Product { Id = 11, CategoryId = 1, Brand = "Converse", Name = "Chuck Taylor All Star", Location = "Main", Size = 8, Price = 101.55M, IsAvailable = true },
                new Product { Id = 12, CategoryId = 1, Brand = "Converse", Name = "Chuck Taylor All Star", Location = "Main", Size = 9, Price = 101.55M, IsAvailable = true },
                new Product { Id = 13, CategoryId = 1, Brand = "Converse", Name = "One Star", Location = "Main", Size = 7, Price = 112M, IsAvailable = true },
                new Product { Id = 14, CategoryId = 1, Brand = "Converse", Name = "One Star", Location = "Main", Size = 8, Price = 112M, IsAvailable = false },
                new Product { Id = 15, CategoryId = 1, Brand = "Converse", Name = "One Star", Location = "Main", Size = 9, Price = 112M, IsAvailable = false },
                new Product { Id = 16, CategoryId = 1, Brand = "Converse", Name = "Pro Leather", Location = "Main", Size = 10, Price = 88M, IsAvailable = false },
                new Product { Id = 17, CategoryId = 1, Brand = "Converse", Name = "Pro Leather", Location = "Main", Size = 11, Price = 88M, IsAvailable = true },
                new Product { Id = 18, CategoryId = 1, Brand = "Converse", Name = "Pro Leather", Location = "Main", Size = 12, Price = 88M, IsAvailable = true },
                new Product { Id = 19, CategoryId = 2, Brand = "Hush Puppies", Name = "Legend", Location = "Little", Size = 7, Price = 101.55M, IsAvailable = true },
                new Product { Id = 20, CategoryId = 2, Brand = "Hush Puppies", Name = "Legend", Location = "Little", Size = 8, Price = 101.55M, IsAvailable = false },
                new Product { Id = 21, CategoryId = 2, Brand = "Hush Puppies", Name = "Legend", Location = "Little", Size = 9, Price = 101.55M, IsAvailable = false },
                new Product { Id = 22, CategoryId = 2, Brand = "Hush Puppies", Name = "Luca", Location = "Little", Size = 7, Price = 199M, IsAvailable = false },
                new Product { Id = 23, CategoryId = 2, Brand = "Hush Puppies", Name = "Luca", Location = "Little", Size = 8, Price = 199M, IsAvailable = true },
                new Product { Id = 24, CategoryId = 2, Brand = "Hush Puppies", Name = "Luca", Location = "Little", Size = 9, Price = 199M, IsAvailable = true },
                new Product { Id = 25, CategoryId = 2, Brand = "Hush Puppies", Name = "Luca", Location = "Little", Size = 10, Price = 199M, IsAvailable = true },
                new Product { Id = 26, CategoryId = 2, Brand = "Hush Puppies", Name = "Norton", Location = "Little", Size = 8, Price = 201.55M, IsAvailable = true },
                new Product { Id = 27, CategoryId = 2, Brand = "Hush Puppies", Name = "Norton", Location = "Little", Size = 9, Price = 201.55M, IsAvailable = true },
                new Product { Id = 28, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 7, Price = 199.95M, IsAvailable = true },
                new Product { Id = 29, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 8, Price = 199.95M, IsAvailable = true },
                new Product { Id = 30, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 9, Price = 199.95M, IsAvailable = true },
                new Product { Id = 31, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 7, Price = 199.95M, IsAvailable = false },
                new Product { Id = 32, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 8, Price = 199.95M, IsAvailable = false },
                new Product { Id = 33, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 9, Price = 199.95M, IsAvailable = false },
                new Product { Id = 34, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 10, Price = 199.95M, IsAvailable = true },
                new Product { Id = 35, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 11, Price = 199.95M, IsAvailable = true },
                new Product { Id = 36, CategoryId = 2, Brand = "Julius Marlow", Name = "Lynch", Location = "Main", Size = 12, Price = 199.95M, IsAvailable = true },
                new Product { Id = 37, CategoryId = 2, Brand = "Julius Marlow", Name = "Wait", Location = "Main", Size = 7, Price = 175.95M, IsAvailable = true },
                new Product { Id = 38, CategoryId = 2, Brand = "Julius Marlow", Name = "Wait", Location = "Main", Size = 8, Price = 175.95M, IsAvailable = true },
                new Product { Id = 39, CategoryId = 2, Brand = "Julius Marlow", Name = "Wait", Location = "Main", Size = 9, Price = 175.95M, IsAvailable = true },
                new Product { Id = 40, CategoryId = 2, Brand = "Julius Marlow", Name = "Wait", Location = "Main", Size = 10, Price = 175.95M, IsAvailable = true },
                new Product { Id = 41, CategoryId = 2, Brand = "Julius Marlow", Name = "Wait", Location = "Main", Size = 11, Price = 175.95M, IsAvailable = true },
                new Product { Id = 42, CategoryId = 2, Brand = "Politix", Name = "Patent", Location = "NextScreen", Size = 7, Price = 199.55M, IsAvailable = true },
                new Product { Id = 43, CategoryId = 2, Brand = "Politix", Name = "Patent", Location = "NextScreen", Size = 8, Price = 199.55M, IsAvailable = false },
                new Product { Id = 44, CategoryId = 2, Brand = "Politix", Name = "Patent", Location = "NextScreen", Size = 9, Price = 199.55M, IsAvailable = false },
                new Product { Id = 45, CategoryId = 2, Brand = "Politix", Name = "Patent", Location = "NextScreen", Size = 7, Price = 199.55M, IsAvailable = false },
                new Product { Id = 46, CategoryId = 2, Brand = "Politix", Name = "Patent", Location = "NextScreen", Size = 8, Price = 199.55M, IsAvailable = true },
                new Product { Id = 47, CategoryId = 2, Brand = "Politix", Name = "Patent", Location = "NextScreen", Size = 9, Price = 199.55M, IsAvailable = true },
                new Product { Id = 48, CategoryId = 3, Brand = "Lacoste", Name = "Lerond Pro", Location = "Little", Size = 10, Price = 122.95M, IsAvailable = true },
                new Product { Id = 49, CategoryId = 3, Brand = "Lacoste", Name = "Lerond Pro", Location = "Little", Size = 8, Price = 122.95M, IsAvailable = true },
                new Product { Id = 50, CategoryId = 3, Brand = "Lacoste", Name = "Lerond Pro", Location = "Little", Size = 9, Price = 122.95M, IsAvailable = true },
                new Product { Id = 51, CategoryId = 3, Brand = "Lacoste", Name = "Lineset 223", Location = "Little", Size = 7, Price = 155M, IsAvailable = true },
                new Product { Id = 52, CategoryId = 3, Brand = "Lacoste", Name = "Lineset 223", Location = "Little", Size = 8, Price = 155M, IsAvailable = true },
                new Product { Id = 53, CategoryId = 3, Brand = "Lacoste", Name = "Lineset 223", Location = "Little", Size = 9, Price = 155M, IsAvailable = true },
                new Product { Id = 54, CategoryId = 3, Brand = "Lacoste", Name = "Lineset 223", Location = "Little", Size = 10, Price = 155M, IsAvailable = true },
                new Product { Id = 55, CategoryId = 3, Brand = "Polo Ralph Lauren", Name = "Longwood", Location = "Little", Size = 8, Price = 199M, IsAvailable = true },
                new Product { Id = 56, CategoryId = 3, Brand = "Polo Ralph Lauren", Name = "Longwood", Location = "Little", Size = 9, Price = 199M, IsAvailable = true },
                new Product { Id = 57, CategoryId = 3, Brand = "Polo Ralph Lauren", Name = "Longwood", Location = "Little", Size = 10, Price = 199M, IsAvailable = true },
                new Product { Id = 58, CategoryId = 3, Brand = "Polo Ralph Lauren", Name = "Longwood", Location = "Little", Size = 11, Price = 199M, IsAvailable = false },
                new Product { Id = 59, CategoryId = 3, Brand = "Polo Ralph Lauren", Name = "Longwood", Location = "Little", Size = 12, Price = 199M, IsAvailable = false },
                new Product { Id = 60, CategoryId = 4, Brand = "Julius Marlow", Name = "Lingo", Location = "Main", Size = 7, Price = 134.96M, IsAvailable = true },
                new Product { Id = 61, CategoryId = 4, Brand = "Julius Marlow", Name = "Lingo", Location = "Main", Size = 8, Price = 134.96M, IsAvailable = true },
                new Product { Id = 62, CategoryId = 4, Brand = "Julius Marlow", Name = "Lingo", Location = "Main", Size = 9, Price = 134.96M, IsAvailable = true },
                new Product { Id = 63, CategoryId = 4, Brand = "Julius Marlow", Name = "Lingo", Location = "Main", Size = 10, Price = 134.96M, IsAvailable = true },
                new Product { Id = 64, CategoryId = 4, Brand = "Julius Marlow", Name = "Lingo", Location = "Main", Size = 11, Price = 134.96M, IsAvailable = true },
                new Product { Id = 65, CategoryId = 4, Brand = "Julius Marlow", Name = "Lingo", Location = "Main", Size = 12, Price = 134.96M, IsAvailable = true },
                new Product { Id = 66, CategoryId = 4, Brand = "Dr Martens", Name = "Adrian", Location = "Main", Size = 7, Price = 339.99M, IsAvailable = true },
                new Product { Id = 67, CategoryId = 4, Brand = "Dr Martens", Name = "Adrian", Location = "Main", Size = 8, Price = 339.99M, IsAvailable = true },
                new Product { Id = 68, CategoryId = 4, Brand = "Dr Martens", Name = "Adrian", Location = "Main", Size = 9, Price = 339.99M, IsAvailable = true },
                new Product { Id = 69, CategoryId = 4, Brand = "Dr Martens", Name = "Adrian", Location = "Main", Size = 10, Price = 339.99M, IsAvailable = true },
                new Product { Id = 70, CategoryId = 4, Brand = "Dr Martens", Name = "Adrian", Location = "Main", Size = 11, Price = 339.99M, IsAvailable = true },
                new Product { Id = 71, CategoryId = 4, Brand = "Dr Martens", Name = "Adrian", Location = "Main", Size = 12, Price = 339.99M, IsAvailable = true },
                new Product { Id = 72, CategoryId = 5, Brand = "Dr Martens", Name = "2976 Chelsea", Location = "Main", Size = 7, Price = 319M, IsAvailable = true },
                new Product { Id = 73, CategoryId = 5, Brand = "Dr Martens", Name = "2976 Chelsea", Location = "Main", Size = 8, Price = 319M, IsAvailable = false },
                new Product { Id = 74, CategoryId = 5, Brand = "Dr Martens", Name = "2976 Chelsea", Location = "Main", Size = 9, Price = 319M, IsAvailable = false },
                new Product { Id = 75, CategoryId = 5, Brand = "Dr Martens", Name = "2976 Chelsea", Location = "Main", Size = 10, Price = 319M, IsAvailable = false },
                new Product { Id = 76, CategoryId = 5, Brand = "Dr Martens", Name = "2976 Chelsea", Location = "Main", Size = 11, Price = 319M, IsAvailable = true },
                new Product { Id = 77, CategoryId = 5, Brand = "Dr Martens", Name = "2976 Chelsea", Location = "Main", Size = 12, Price = 319M, IsAvailable = true },
                new Product { Id = 78, CategoryId = 5, Brand = "Dr Martens", Name = "1460 Pascal", Location = "Main", Size = 7, Price = 356M, IsAvailable = true },
                new Product { Id = 79, CategoryId = 5, Brand = "Dr Martens", Name = "1460 Pascal", Location = "Main", Size = 8, Price = 356M, IsAvailable = false },
                new Product { Id = 80, CategoryId = 5, Brand = "Dr Martens", Name = "1460 Pascal", Location = "Main", Size = 9, Price = 356M, IsAvailable = false },
                new Product { Id = 81, CategoryId = 5, Brand = "Dr Martens", Name = "1460 Pascal", Location = "Main", Size = 10, Price = 356M, IsAvailable = false },
                new Product { Id = 82, CategoryId = 5, Brand = "Dr Martens", Name = "1460 Pascal", Location = "Main", Size = 11, Price = 356M, IsAvailable = true },
                new Product { Id = 83, CategoryId = 5, Brand = "Dr Martens", Name = "1460 Pascal", Location = "Main", Size = 12, Price = 356M, IsAvailable = true },
                new Product { Id = 84, CategoryId = 5, Brand = "Wild Rhino", Name = "1460 Pascal", Location = "Little", Size = 7, Price = 199.95M, IsAvailable = true },
                new Product { Id = 85, CategoryId = 5, Brand = "Wild Rhino", Name = "1460 Pascal", Location = "Little", Size = 8, Price = 199.95M, IsAvailable = true },
                new Product { Id = 86, CategoryId = 5, Brand = "Wild Rhino", Name = "1460 Pascal", Location = "Little", Size = 9, Price = 199.95M, IsAvailable = true },
                new Product { Id = 87, CategoryId = 5, Brand = "Wild Rhino", Name = "1460 Pascal", Location = "Little", Size = 10, Price = 199.95M, IsAvailable = true },
                new Product { Id = 88, CategoryId = 5, Brand = "Wild Rhino", Name = "1460 Pascal", Location = "Little", Size = 11, Price = 199.95M, IsAvailable = true });



        }
    }
}
